language: python
python:
  - 2.7
notifications:
  email: false
env:
  global:
    - TORNPSQL=postgres://postgres:@127.0.0.1:5432/tornpsql
    - TORNUSER=postgres
services: postgres
addons:
  postgresql: "9.3"
before_script:
  - pip install codecov
  - python setup.py install
  - psql -U postgres -c 'create database tornpsql;'
  - psql tornpsql -f tests/test.sql
script:
  - coverage run -m unittest discover -s tests
after_success: codecov
