language: python
python:
  - 2.7
notifications:
  email: false
env:
  global:
    - DATABASE_URL=postgres://postgres:@127.0.0.1:5432/tornpsql
    - DATABASE_USER=postgres
services: postgres
addons:
  postgresql: "9.3"
before_script:
  - pip install codecov
  - python setup.py install
  - pip install nose rednose nose-cov codecov
  - psql -U postgres -c 'create database tornpsql;'
  - psql tornpsql -f tests/test.sql
script: nosetests --rednose --with-cov
after_success: codecov
